[tools]
pre-commit = "latest"
python = "3.13"
trivy = "latest"
uv = "latest"
vim = "latest"

[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[env]
APP_REPO = 'devops-study-app'
GITOPS_REPO = 'devops-study-app-gitops'

[hooks] # To run whenever sshing into container
enter = "bash ./scripts/setup_project" 
